-- 코드를 작성해주세요
SELECT INFOS.ID, INFOS.EMAIL, INFOS.FIRST_NAME, INFOS.LAST_NAME
FROM DEVELOPER_INFOS INFOS
WHERE INFOS.SKILL_1 = "Python" OR INFOS.SKILL_2 = "Python" OR INFOS.SKILL_3 = "Python"
ORDER BY INFOS.ID;