-- 코드를 작성해주세요
SELECT INFO.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
FROM ITEM_INFO INFO
WHERE INFO.ITEM_ID IN (SELECT TREE.ITEM_ID
                      FROM ITEM_INFO INFO
                      JOIN ITEM_TREE TREE 
                      ON INFO.ITEM_ID = TREE.PARENT_ITEM_ID
                      WHERE INFO.RARITY = 'RARE')
ORDER BY INFO.ITEM_ID DESC;

