-- 코드를 입력하세요
-- TITLE(BOARD), BOARD_ID(BOARD), REPLY_ID(REPLY), WRITER_ID(BOARD), CONTENTS(BOARD), CREATED_DATE(BOARD)
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY R ON B.BOARD_ID = R.BOARD_ID
WHERE B.CREATED_DATE >= '2022-10-01' AND B.CREATED_DATE < '2022-11-01'
ORDER BY R.CREATED_DATE , B.TITLE;